"""
Process-mapping walker for Linux 6.1+ maple-tree VMAs.

All kernel struct offsets are loaded from a kernelinfo.conf dict (``ki``) that
is generated by GDB at kernel-build time, so the walker works across kernel
releases without code changes.
"""

import struct


class ProcessMappings:
    """
    Walks the maple-tree VMA list of the current process and caches the result.

    Usage::

        pm = ProcessMappings(panda, ki)
        pm.refresh(cpu)          # populate pm.mappings
        pm.is_heap(pm.mappings[0])
    """

    # ---------------------------------------------------------------------------
    # enode pointer tag bits — fixed by the maple tree ABI
    # ---------------------------------------------------------------------------
    _MAPLE_NODE_MASK       = 0xFF
    _MAPLE_NODE_TYPE_SHIFT = 3
    _MAPLE_NODE_TYPE_MASK  = 0xF

    # maple_type enum values — fixed by the kernel ABI
    _MTYPE_DENSE    = 0
    _MTYPE_LEAF_64  = 1
    _MTYPE_RANGE_64 = 2
    _MTYPE_ARANGE64 = 3

    def __init__(self, panda, ki):
        """
        Parameters
        ----------
        panda : pandare.Panda
        ki    : dict  –  flat key->int dict from kernelinfo.conf
        """
        self._panda = panda

        # Maple-tree offsets
        self._MM_MT_OFFSET       = ki['mm.mm_mt_offset']
        self._MT_MA_ROOT_OFFSET  = ki['maple.mt.ma_root_offset']
        # struct maple_node — dense layout
        self._MN_SLOT0_OFFSET    = ki['maple.mn.slot0_offset']
        self._MN_NUM_SLOTS       = ki['maple.mn.num_slots']
        # struct maple_range_64 / maple_leaf_64
        self._MR64_PIVOT0_OFFSET = ki['maple.mr64.pivot0_offset']
        self._MR64_NUM_PIVOTS    = ki['maple.mr64.num_pivots']
        self._MR64_SLOT_OFFSET   = ki['maple.mr64.slot0_offset']
        self._MR64_META_OFFSET   = ki['maple.mr64.meta_offset']
        self._MR64_NUM_SLOTS     = ki['maple.mr64.num_slots']
        # struct maple_arange_64
        self._MA64_PIVOT0_OFFSET = ki['maple.ma64.pivot0_offset']
        self._MA64_NUM_PIVOTS    = ki['maple.ma64.num_pivots']
        self._MA64_SLOT_OFFSET   = ki['maple.ma64.slot0_offset']
        self._MA64_META_OFFSET   = ki['maple.ma64.meta_offset']
        self._MA64_NUM_SLOTS     = ki['maple.ma64.num_slots']

        # vm_area_struct offsets
        self._VMA_VM_START = ki['vma.vm_start_offset']
        self._VMA_VM_END   = ki['vma.vm_end_offset']
        self._VMA_VM_FLAGS = ki['vma.vm_flags_offset']
        self._VMA_VM_FILE  = ki['vma.vm_file_offset']

        # mm_struct offsets
        self._MM_START_BRK   = ki['mm.start_brk_offset']
        self._MM_BRK         = ki['mm.brk_offset']
        self._MM_START_STACK = ki['mm.start_stack_offset']

        # task_struct / file / dentry offsets
        self._TASK_MM       = ki['task.mm_offset']
        self._F_PATH_DENTRY = ki['fs.f_path_dentry_offset']
        self._D_INAME       = ki['path.d_iname_offset']

        #: Most-recently refreshed list of mapping dicts.
        self.mappings = []


    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def refresh(self, cpu):
        """Walk the maple tree of the current process and update ``self.mappings``."""
        panda = self._panda
        proc = panda.plugins['osi'].get_current_process(cpu)
        if proc == panda.ffi.NULL:
            self.mappings = []
            print('[analysis1] refresh: current process is NULL')
            return

        task_addr = int(proc.taskd)
        pname     = panda.ffi.string(proc.name).decode('utf-8', 'replace')

        mm_ptr = self._vmread64(cpu, task_addr + self._TASK_MM)
        if not mm_ptr:
            self.mappings = []
            print(f'[analysis1] refresh: mm is NULL for {pname!r}')
            return

        ma_root_addr = mm_ptr + self._MM_MT_OFFSET + self._MT_MA_ROOT_OFFSET
        ma_root = self._vmread64(cpu, ma_root_addr)
        if not ma_root:
            self.mappings = []
            print(f'[analysis1] refresh: ma_root is NULL for {pname!r}')
            return

        node_addr = self._mt_node_addr(ma_root)
        print(f'[analysis1] refresh: task=0x{task_addr:x} mm=0x{mm_ptr:x} ma_root=0x{ma_root:x} proc={pname!r}')

        # DBG: dump the raw 256-byte maple node so we can see its actual contents
        if self._DBG:
            try:
                raw_node = self._panda.virtual_memory_read(cpu, node_addr, 256)
                hex_lines = []
                for i in range(0, 256, 16):
                    chunk = raw_node[i:i+16]
                    hex_str = ' '.join(f'{b:02x}' for b in chunk)
                    hex_lines.append(f'  {node_addr + i:016x}: {hex_str}')
                print(f'[analysis1][dbg] raw node dump @ 0x{node_addr:x}:')
                for line in hex_lines:
                    print(line)
            except Exception as e:
                print(f'[analysis1][dbg] raw node dump failed: {e}')

        raw_vmas = []
        self._mt_walk_node(cpu, ma_root, mm_ptr, raw_vmas)
        raw_vmas.sort(key=lambda v: v['base'])

        self.mappings = raw_vmas
        print(f'[analysis1] refreshed {len(self.mappings)} mappings for {pname!r}')
        for m in self.mappings:
            print(
                f'[analysis1]   0x{m["base"]:016x}-0x{m["base"]+m["size"]:016x} '
                f'flags=0x{m["flags"]:x} name={m["name"]!r}'
            )

    @staticmethod
    def is_heap(mapping):
        """Return True if *mapping* is a heap/stack/anonymous region."""
        return mapping['name'] in ('[heap]', '[anon]', '[stack]')

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _vmread64(self, cpu, addr):
        """Read a little-endian u64 from guest virtual memory; return None on fault."""
        try:
            raw = self._panda.virtual_memory_read(cpu, addr, 8)
            return struct.unpack_from('<Q', raw)[0]
        except Exception:
            return None

    def _vmread8(self, cpu, addr):
        """Read a single byte from guest virtual memory; return None on fault."""
        try:
            raw = self._panda.virtual_memory_read(cpu, addr, 1)
            return raw[0]
        except Exception:
            return None

    @staticmethod
    def _mt_node_addr(enode):
        return enode & ~ProcessMappings._MAPLE_NODE_MASK

    @staticmethod
    def _mt_node_type(enode):
        return (enode >> ProcessMappings._MAPLE_NODE_TYPE_SHIFT) & ProcessMappings._MAPLE_NODE_TYPE_MASK

    @staticmethod
    def _mt_is_leaf(node_type):
        return node_type in (ProcessMappings._MTYPE_DENSE, ProcessMappings._MTYPE_LEAF_64)

    def _read_vma(self, cpu, vma_ptr, mm_ptr):
        """Read a vm_area_struct and return a mapping dict, or None if invalid."""
        vm_start = self._vmread64(cpu, vma_ptr + self._VMA_VM_START)
        vm_end   = self._vmread64(cpu, vma_ptr + self._VMA_VM_END)
        self._dbg(
            f'  _read_vma(0x{vma_ptr:x}): vm_start={hex(vm_start) if vm_start is not None else None}'
            f' vm_end={hex(vm_end) if vm_end is not None else None}'
        )
        if vm_start is None or vm_end is None:
            return None
        if vm_end <= vm_start:
            return None

        vm_flags = self._vmread64(cpu, vma_ptr + self._VMA_VM_FLAGS) or 0
        vm_file  = self._vmread64(cpu, vma_ptr + self._VMA_VM_FILE)

        name = None
        if vm_file:
            dentry_ptr = self._vmread64(cpu, vm_file + self._F_PATH_DENTRY)
            if dentry_ptr:
                try:
                    raw = self._panda.virtual_memory_read(cpu, dentry_ptr + self._D_INAME, 32)
                    name = raw.split(b'\x00', 1)[0].decode('utf-8', 'replace') or None
                except Exception:
                    name = None
        else:
            start_brk   = self._vmread64(cpu, mm_ptr + self._MM_START_BRK)
            brk         = self._vmread64(cpu, mm_ptr + self._MM_BRK)
            start_stack = self._vmread64(cpu, mm_ptr + self._MM_START_STACK)
            if start_brk is not None and brk is not None and vm_start <= start_brk and vm_end >= brk:
                name = '[heap]'
            elif start_stack is not None and vm_start <= start_stack <= vm_end:
                name = '[stack]'
            else:
                name = '[anon]'

        return {
            'base':  vm_start,
            'size':  vm_end - vm_start,
            'flags': vm_flags,
            'name':  name,
            'file':  None,
        }

    def _mr64_data_end(self, cpu, node_addr, type_name, depth):
        """Mirror the kernel's ma_data_end() for maple_range_64 / maple_leaf_64.

        The kernel decides the slot count as follows:
          last_piv = pivot[num_pivots - 1]
          if last_piv == 0:         return meta.end          (short/sparse node)
          if last_piv == ULONG_MAX: return num_pivots - 1    (root whose range ends at ULONG_MAX)
          else:                     return num_pivots         (mid-range node, all slots used)

        Returns the number of slots to scan, or None on read failure.
        """
        num_pivots   = self._MR64_NUM_PIVOTS          # e.g. 15 for a 16-slot node
        last_piv_off = self._MR64_PIVOT0_OFFSET + (num_pivots - 1) * 8
        last_piv     = self._vmread64(cpu, node_addr + last_piv_off)
        meta_end     = self._vmread8(cpu,  node_addr + self._MR64_META_OFFSET)

        self._dbg(
            f'walk depth={depth} {type_name} node=0x{node_addr:x}: '
            f'last_pivot[{num_pivots-1}] @ +0x{last_piv_off:x} = '
            f'{hex(last_piv) if last_piv is not None else None}, '
            f'meta.end={meta_end!r} '
            f'(pivot0=+{self._MR64_PIVOT0_OFFSET} num_pivots={num_pivots} '
            f'slot0=+{self._MR64_SLOT_OFFSET} num_slots={self._MR64_NUM_SLOTS})'
        )

        if last_piv is None or meta_end is None:
            self._dbg(f'walk depth={depth} {type_name}: read failure — aborting branch')
            return None

        ULONG_MAX = 0xffffffffffffffff
        if last_piv == 0:
            num_slots = min(meta_end + 1, self._MR64_NUM_SLOTS)
            self._dbg(f'walk depth={depth} {type_name}: last_pivot=0 → meta_end={meta_end} → {num_slots} slot(s)')
        elif last_piv == ULONG_MAX:
            num_slots = num_pivots      # slots 0..num_pivots-1 (last slot is the ULONG_MAX sentinel range)
            self._dbg(f'walk depth={depth} {type_name}: last_pivot=ULONG_MAX → {num_slots} slot(s)')
        else:
            num_slots = self._MR64_NUM_SLOTS   # all slots including the one past the last pivot
            self._dbg(f'walk depth={depth} {type_name}: last_pivot=0x{last_piv:x} → full {num_slots} slot(s)')

        return num_slots

    # -----------------------------------------------------------------------
    # DBG helpers — set _DBG = False to silence all maple-walk traces at once
    # -----------------------------------------------------------------------
    _DBG = True

    def _dbg(self, msg):
        if self._DBG:
            print(f'[analysis1][dbg] {msg}')

    def _mt_walk_node(self, cpu, enode, mm_ptr, results, depth=0):
        """Recursively walk a maple tree node, collecting leaf VMA entries."""
        if depth > 64:
            print('[analysis1] maple_walk: depth limit reached, aborting branch')
            return

        if enode is None or enode < 0x1000:
            self._dbg(f'walk depth={depth}: enode={enode!r} below threshold, skipping')
            return

        node_type = self._mt_node_type(enode)
        node_addr = self._mt_node_addr(enode)

        self._dbg(
            f'walk depth={depth}: enode=0x{enode:x} '
            f'node_type={node_type} node_addr=0x{node_addr:x}'
        )

        if node_addr < 0x1000:
            self._dbg(f'walk depth={depth}: node_addr too small, skipping')
            return

        if node_type == self._MTYPE_DENSE and depth == 0:
            # Single-entry root: enode IS the raw VMA pointer (no node wrapper)
            self._dbg(f'walk depth=0 DENSE: treating enode 0x{enode:x} as direct VMA ptr')
            entry = self._read_vma(cpu, enode, mm_ptr)
            self._dbg(f'walk depth=0 DENSE: _read_vma → {entry}')
            if entry:
                results.append(entry)
            return

        if node_type == self._MTYPE_DENSE:
            self._dbg(f'walk depth={depth} DENSE node at 0x{node_addr:x}: scanning {self._MN_NUM_SLOTS} slots')
            for i in range(self._MN_NUM_SLOTS):
                slot_addr = node_addr + self._MN_SLOT0_OFFSET + i * 8
                slot_val = self._vmread64(cpu, slot_addr)
                self._dbg(f'  dense slot[{i}] @ 0x{slot_addr:x} = {hex(slot_val) if slot_val is not None else None}')
                if slot_val and slot_val >= 0x1000:
                    entry = self._read_vma(cpu, slot_val, mm_ptr)
                    self._dbg(f'  dense slot[{i}]: _read_vma → {entry}')
                    if entry:
                        results.append(entry)

        elif node_type in (self._MTYPE_LEAF_64, self._MTYPE_RANGE_64):
            type_name = 'LEAF_64' if node_type == self._MTYPE_LEAF_64 else 'RANGE_64'
            num_slots = self._mr64_data_end(cpu, node_addr, type_name, depth)
            if num_slots is None:
                return
            for i in range(num_slots):
                slot_addr = node_addr + self._MR64_SLOT_OFFSET + i * 8
                slot_val = self._vmread64(cpu, slot_addr)
                self._dbg(
                    f'  {type_name} slot[{i}] @ 0x{slot_addr:x} = '
                    f'{hex(slot_val) if slot_val is not None else None}'
                )
                if not slot_val or slot_val < 0x1000:
                    self._dbg(f'  {type_name} slot[{i}]: null/small, skipping')
                    continue
                if self._mt_is_leaf(node_type):
                    entry = self._read_vma(cpu, slot_val, mm_ptr)
                    self._dbg(f'  {type_name} slot[{i}]: _read_vma(0x{slot_val:x}) → {entry}')
                    if entry:
                        results.append(entry)
                else:
                    self._mt_walk_node(cpu, slot_val, mm_ptr, results, depth + 1)

        elif node_type == self._MTYPE_ARANGE64:
            # arange_64 always uses meta.end (ma_data_end returns it unconditionally)
            meta_addr = node_addr + self._MA64_META_OFFSET
            meta_end = self._vmread8(cpu, meta_addr)
            self._dbg(
                f'walk depth={depth} ARANGE64 node=0x{node_addr:x}: '
                f'meta @ 0x{meta_addr:x} → meta_end={meta_end!r} '
                f'(MA64_META_OFFSET={self._MA64_META_OFFSET}, MA64_NUM_SLOTS={self._MA64_NUM_SLOTS})'
            )
            if meta_end is None:
                self._dbg(f'walk depth={depth} ARANGE64: meta_end read failed — aborting branch')
                return
            num_slots = min(meta_end + 1, self._MA64_NUM_SLOTS)
            self._dbg(f'walk depth={depth} ARANGE64: scanning {num_slots} slot(s)')
            for i in range(num_slots):
                slot_addr = node_addr + self._MA64_SLOT_OFFSET + i * 8
                slot_val = self._vmread64(cpu, slot_addr)
                self._dbg(
                    f'  ARANGE64 slot[{i}] @ 0x{slot_addr:x} = '
                    f'{hex(slot_val) if slot_val is not None else None}'
                )
                if not slot_val or slot_val < 0x1000:
                    self._dbg(f'  ARANGE64 slot[{i}]: null/small, skipping')
                    continue
                self._mt_walk_node(cpu, slot_val, mm_ptr, results, depth + 1)

        else:
            print(f'[analysis1] maple_walk: unknown node type {node_type} at enode=0x{enode:x}')
